version: "2"
services:
  examplediscovery:
    image: "example-discovery:0.0.1-SNAPSHOT"
    hostname: examplediscovery
    ports:
     - "8761:8761"

  exampleconfig:
    image: "example-config:0.0.1-SNAPSHOT"
    hostname: exampleconfig
    links:
      - examplediscovery
    environment:
       EUREKA_HOST: examplediscovery
       EUREKA_PORT: 8761
       CONFIG_HOST: exampleconfig
       CONFIG_PORT: 8888

  exampleservice:
    image: example-service:0.0.1-SNAPSHOT
    hostname: exampleservice
    links:
      - examplediscovery
      - exampleconfig
    environment:
       EUREKA_HOST: examplediscovery
       EUREKA_PORT: 8761
       CONFIG_HOST: exampleconfig
       CONFIG_PORT: 8888
       SERVER_PORT: 8080
    depends_on:
        - exampleconfig

  examplegateway:
    image: example-gateway:0.0.1-SNAPSHOT
    hostname: examplegateway
    links:
      - examplediscovery
      - exampleconfig
    environment:
       EUREKA_HOST: examplediscovery
       EUREKA_PORT: 8761
       CONFIG_HOST: exampleconfig
       CONFIG_PORT: 8888
       SERVER_PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
        - exampleconfig
