# application.yml
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
server:
  port: 8888

logging:
  level:
    com:
      netflix:
        discovery: DEBUG
